function [ x_pro, P ] = Model_mix4( x1, x2, x3, x4, x5, P1, P2, P3, P4, P5, u )
x_pro = x1*u(1) + x2*u(2) + x3*u(3) + x4*u(4) + x5*u(5);
P = u(1)*(P1 + (x1 - x_pro)*((x1 - x_pro)')) + ...
    u(2)*(P2 + (x2 - x_pro) * ((x2 - x_pro)')) + ...
    u(3) * (P3 + (x3 - x_pro) * ((x3 - x_pro)')) + ...
    u(4) * (P4 + (x4 - x_pro) * ((x4 - x_pro)')) + ...
    u(5) * (P5 + (x5 - x_pro) * ((x5 - x_pro)'));
end

